name: Deploy Ghost Theme

on:
  push:
    branches:
      - main
    paths:
      - '**/*' # 모든 파일을 감지

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install zip and jq
      run: |
        sudo apt-get update
        sudo apt-get install zip jq -y

    - name: Create ZIP of the theme
      run: |
        THEME_NAME="my-theme"
        zip -r ${THEME_NAME}.zip . -x ".git/*" -x ".github/*"
        echo "Created ZIP file:"
        ls -l ${THEME_NAME}.zip

    - name: Upload Theme to Ghost
      env:
        GHOST_ADMIN_API_URL: ${{ secrets.GHOST_ADMIN_API_URL }}
        GHOST_ADMIN_API_KEY: ${{ secrets.GHOST_ADMIN_API_KEY }}
      run: |
        # 테마 파일 찾기
        THEME_FILE=$(ls *.zip | head -n 1)
        if [ -z "$THEME_FILE" ]; then
          echo "No theme file found."
          exit 1
        fi
        echo "Found theme file: $THEME_FILE"

        # Ghost Admin API를 통해 테마 업로드
        RESPONSE=$(curl -s -w "\n%{http_code}" -o response.json -X POST "${GHOST_ADMIN_API_URL}/themes/upload/" \
          -H "Authorization: Ghost ${GHOST_ADMIN_API_KEY}" \
          -F "file=@${THEME_FILE}" \
          -H "Content-Type: multipart/form-data")

        HTTP_STATUS=$(tail -n1 response.json)
        if [ "$HTTP_STATUS" -ne 201 ]; then
          echo "Upload failed with status code $HTTP_STATUS"
          cat response.json
          exit 1
        fi

        echo "Upload successful. Response:"
        cat response.json

        THEME_NAME=$(jq -r '.themes[0].name' response.json)
        if [ -z "$THEME_NAME" ]; then
          echo "Failed to get theme name from response."
          cat response.json
          exit 1
        fi
        echo "Theme name from response: $THEME_NAME"

    - name: Activate uploaded theme
      env:
        GHOST_ADMIN_API_URL: ${{ secrets.GHOST_ADMIN_API_URL }}
        GHOST_ADMIN_API_KEY: ${{ secrets.GHOST_ADMIN_API_KEY }}
      run: |
        THEME_NAME=$(jq -r '.themes[0].name' response.json)
        if [ -z "$THEME_NAME" ]; then
          echo "Failed to get theme name for activation."
          exit 1
        fi

        # 업로드된 테마를 활성화
        ACTIVATE_RESPONSE=$(curl -s -w "\n%{http_code}" -o activate_response.json -X PUT "${GHOST_ADMIN_API_URL}/themes/${THEME_NAME}/activate" \
          -H "Authorization: Ghost ${GHOST_ADMIN_API_KEY}" \
          -H "Content-Type: application/json")

        ACTIVATE_HTTP_STATUS=$(tail -n1 activate_response.json)
        if [ "$ACTIVATE_HTTP_STATUS" -ne 200 ]; then
          echo "Activation failed with status code $ACTIVATE_HTTP_STATUS"
          cat activate_response.json
          exit 1
        fi

        echo "Activate response:"
        cat activate_response.json
